### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by jerry011235** [microacup/hexo-theme-micorb#1]
1.点击搜索按钮能否弹窗?
2.[Valine评论系统](https://valine.js.org)
3.两个扇形导航([1](https://codepen.io/trvr/pen/LhBjq),[2](https://codepen.io/shahbokhari/pen/AbHFx)),如果觉得漂亮的话,能否添加?

**Comment by microacup** [comment]
1. 搜索放在新页面中考虑的是减少首页复杂度（也是这个主题的的核心），现在只有在搜索也才加载js依赖。这个可能暂时不会做。
2. 可以尝试支持
3. 感兴趣的可以提交pr

**Comment by jerry011235** [comment]
好的，谢谢，另外加个返回顶部吧。

**Comment by microacup** [comment]
@jerry011235 点击顶部图标返回顶部，参考twitter

**Comment by jerry011235** [comment]
[懒加载](https://github.com/tuupola/jquery_lazyload)、prettyPhoto或fancybox能加上吗？

**Comment by microacup** [comment]
@jerry011235 暂不考虑在主分支添加。可以fork
