### ISSUE TITLE
搜索、归档和表格

### ISSUE THREAD

**Issue by ghost** [microacup/hexo-theme-micorb#2]
很喜欢这个简洁的主题！
我遇到3个问题：
1. 搜索页的配置方法，有相关的介绍吗？
2. 是否能加入归档页面，便于读者的浏览以及作者的整理。
3. 似乎不支持markdown的表格语法？

**Comment by microacup** [comment]
1. 搜索页目前使用的是本地搜索[hexo-generator-search](https://github.com/PaicHyperionDev/hexo-generator-search) ，配置方式参考插件介绍
2. 已支持，需要在config中配置
3. 已支持

**Comment by ghost** [comment]
更新已用上，非常感谢！
